stages:
    - lint
    - build
    - test

variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    npm_config_cache: '$CI_PROJECT_DIR/.npm'
    CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    paths:
        - .cache/pip/
        - venv/
        - staticfiles/
        - cache/Cypress
        - node_modules
        - build

# Defines the job in Static Analysis
django-lint:
    image: python:3.11-alpine
    stage: lint
    tags:
        - python
    before_script:
        - .gitlab/django_before_install.sh
        - source venv/bin/activate
    script:
        - pylama .

# Defines the job in build
# Checks if migrations files are missing
django-migrations:
    image: python:3.11-alpine
    stage: build
    tags:
        - python
    needs: ['django-lint']
    before_script:
        - .gitlab/django_before_install.sh
        - source venv/bin/activate
    script:
        - python3 manage.py makemigrations --check
        - python3 manage.py migrate --check
        - python3 manage.py check
        - python3 manage.py check --database default
        - python3 manage.py check --deploy

# Defines the job in test
django-tests:
    image: python:3.11-alpine
    stage: test
    tags:
        - python
    needs: ['django-migrations', 'django-lint']
    before_script:
        - .gitlab/django_before_install.sh
        - source venv/bin/activate
    script:
        - coverage run manage.py test -v2
        - coverage xml
        - coverage report

    coverage: '/TOTAL.*\s+(\d+%)$/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml

# Defines the job for Cypress e2e tests
cypress-e2e:
    image: cypress/base:18.16.0
    stage: test
    needs: ['django-migrations', 'django-lint']
    before_script:
        - .gitlab/cypress_before_install.sh
    script:
        # start the server in the background
        - python3 manage.py runserver &
        # run Cypress tests
        - npx cypress run --headless
